name: Deploy test page
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'test-page/**'
      - '.github/workflows/deploy-test-page.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - run: |
          npm install
          npm run build
        working-directory: test-page
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: test-page/dist
          CLEAN: true
