on:
  push:
    branches:
      - master
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npx release-it --npm.skipChecks --ci
        env:
          GITHUB_TOKEN: ${{ secrets.TJK_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TJK_TOKEN }}
